[build]
builder = "nixpacks"

[build.nixpacks]
nixPkgs = ["nodejs_20", "pnpm"]
installCmd = "pnpm install --frozen-lockfile=false"
buildCmd = "pnpm --filter discord-bot build"

[deploy]
startCommand = "pnpm --filter discord-bot start"
